# Generated by Django 4.1.2 on 2022-10-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
