# Generated by Django 4.1.2 on 2022-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalportfolio', '0002_alter_projects_link_alter_projects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
