# Generated by Django 4.1.2 on 2022-10-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalportfolio', '0004_certificates_alter_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/contacts/')),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
